export { default as banner } from './banner.jpg';
export { default as imgToGallery } from './imgToGallery.jpg';
export { default as creationSectionBackground } from './creationSectionBackground.jpg';
export { default as loginBackground } from './login-background.mp4';
export { default as spinnerDark } from './spinner-dark.svg';
export { default as spinner } from './spinner.svg';
export { default as logoPng } from './logo.png';
export { default as logoWhite } from './logo-white.png';
export { default as aboutPageImage1} from './about-page-image-1.jpeg';
export { default as aboutPageImage2} from './about-page-image-2.jpeg';
export { default as aboutPageImage3} from './about-page-image-3.jpeg';
export { default as aboutPageImage4} from './about-page-image-4.jpeg';
