version: '3'

services:
  starlux:

    container_name: starlux

    build: 
      context: .
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3003:8000"

    env_file:
      - .env.production
