version: '3'

services:
  starlux:

    container_name: starlux

    build: 
      context: .
      dockerfile: Dockerfile


    restart: always

    ports:
      - "3003:8000"

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    
    volumes:
      - starlux-data:/app


volumes:
  starlux-data:
