# Generated by Django 2.2.24 on 2023-11-10 13:08

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20231110_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.upload_to),
        ),
    ]
