// Generated by https://quicktype.io

export interface User {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
}

export interface CreateUser {
    email:      string;
    first_name: string;
    last_name:  string;
    password:   string;
}
